server:
  port: 9999
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vueblog?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      write-dates-as-timestamps: true
